
andesharvest:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: dbt_user
      password: dbt_password
      port: 5432
      dbname: andesharvest_db
      schema: raw_data
      threads: 4
